export const laporanData = [
  {
    id: 200,
    user_id: 76,
    jasa_id: 1,
    namaPengguna: 'Ahmad Saputra',
    penyediaJasa: 'Adi Pratama',
    namaJasa: 'Tambal Ban',
    status: 'Diblokir',
    jenisLaporan: 'Penipuan',
    tanggal: '2024-11-15',
    lokasi: 'Jakarta Selatan',
    harga: 55000,
    metodePembayaran: 'Transfer',
  },
  {
    id: 201,
    user_id: 77,
    jasa_id: 4,
    namaPengguna: 'Dewi Lestari',
    penyediaJasa: 'Indah Kartika',
    namaJasa: 'Layanan Bersih-Bersih',
    status: 'Ditangguhkan',
    jenisLaporan: 'Tidak Profesional',
    tanggal: '2024-11-18',
    lokasi: 'Depok',
    harga: 125000,
    metodePembayaran: 'Cash',
  },
  {
    id: 202,
    user_id: 78,
    jasa_id: 10,
    namaPengguna: 'Putri Ayu',
    penyediaJasa: 'Yudi Prasetyo',
    namaJasa: 'Pemotongan Rumput',
    status: 'Peringatan',
    jenisLaporan: 'Pelanggaran Aturan',
    tanggal: '2024-11-20',
    lokasi: 'Malang',
    harga: 90000,
    metodePembayaran: 'Transfer',
  },
  {
    id: 203,
    user_id: 79,
    jasa_id: 7,
    namaPengguna: 'Hendra Wijaya',
    penyediaJasa: 'Fitri Santoso',
    namaJasa: 'Perbaikan Kran Air',
    status: 'Ditinjau',
    jenisLaporan: 'Pelayanan Buruk',
    tanggal: '2024-11-22',
    lokasi: 'Bekasi',
    harga: 100000,
    metodePembayaran: 'Transfer',
  },
  {
    id: 204,
    user_id: 80,
    jasa_id: 6,
    namaPengguna: 'Joko Pranoto',
    penyediaJasa: 'Wahyu Adi',
    namaJasa: 'Perbaikan Atap Bocor',
    status: 'Ditinjau',
    jenisLaporan: 'Penipuan',
    tanggal: '2024-11-23',
    lokasi: 'Medan',
    harga: 160000,
    metodePembayaran: 'Cash',
  },
];
