export const pesananJasaData = [
  {
    id: 50,
    kategori: 'Otomotif',
    nama: 'Budi Santoso',
    harga: 50000,
    status: 'Selesai',
  },
  {
    id: 51,
    kategori: 'Otomotif',
    nama: 'Ahmad Saputra',
    harga: 55000,
    status: 'Berjalan',
  },
  {
    id: 52,
    kategori: 'Hewan Peliharaan',
    nama: 'Dewi Lestari',
    harga: 30000,
    status: 'Selesai',
  },
  {
    id: 53,
    kategori: 'Hewan Peliharaan',
    nama: 'Putri Ayu',
    harga: 120000,
    status: 'Menunggu',
  },
  {
    id: 54,
    kategori: 'Pertukangan',
    nama: 'Hendra Wijaya',
    harga: 150000,
    status: 'Berjalan',
  },
  {
    id: 55,
    kategori: 'Pertukangan',
    nama: 'Joko Pranoto',
    harga: 160000,
    status: 'Selesai',
  },
  {
    id: 56,
    kategori: 'Pembersihan',
    nama: 'Rina Setiani',
    harga: 100000,
    status: 'Menunggu',
  },
  {
    id: 57,
    kategori: 'Elektronik',
    nama: 'Faisal Kurnia',
    harga: 75000,
    status: 'Berjalan',
  },
  {
    id: 58,
    kategori: 'Elektronik',
    nama: 'Agus Salim',
    harga: 75000,
    status: 'Selesai',
  },
  {
    id: 59,
    kategori: 'Perbaikan Rumah',
    nama: 'Dian Sasmita',
    harga: 200000,
    status: 'Menunggu',
  },
  {
    id: 60,
    kategori: 'Perbaikan Rumah',
    nama: 'Andi Wirawan',
    harga: 200000,
    status: 'Berjalan',
  },
  {
    id: 61,
    kategori: 'Pengantaran',
    nama: 'Siti Mulyani',
    harga: 40000,
    status: 'Selesai',
  },
  {
    id: 62,
    kategori: 'Pengantaran',
    nama: 'Rudi Hartono',
    harga: 42000,
    status: 'Menunggu',
  },
  {
    id: 63,
    kategori: 'Perawatan Taman',
    nama: 'Bayu Pratama',
    harga: 80000,
    status: 'Selesai',
  },
  {
    id: 64,
    kategori: 'Perawatan Taman',
    nama: 'Tono Setiawan',
    harga: 85000,
    status: 'Menunggu',
  },
];
