export const pesananJasaData = [
  {
    id: 50,
    kategori: 'Otomotif',
    userid: 75,
    nama: 'Budi Santoso',
    jasaid: 1,
    metode_pembayaran: 'Transfer',
    status: 'Selesai',
    tanggal: '2024-10-10',
    jam: '10:00',
    lokasi: 'Jakarta Selatan',
    detailjasa:
      'Ban belakang motor bocor, butuh tambalan cepat di dekat kantor.',
    harga: 50000,
  },
  {
    id: 51,
    kategori: 'Hewan Peliharaan',
    userid: 76,
    nama: 'Ahmad Saputra',
    jasaid: 2,
    metode_pembayaran: 'Cash',
    status: 'Berjalan',
    tanggal: '2024-10-12',
    jam: '14:30',
    lokasi: 'Bandung',
    detailjasa:
      'Saya butuh bantuan untuk memberi makan kucing peliharaan saya yang sedang sakit.',
    harga: 55000,
  },
  {
    id: 52,
    kategori: 'Pertukangan',
    userid: 77,
    nama: 'Dewi Lestari',
    jasaid: 3,
    metode_pembayaran: 'Transfer',
    status: 'Selesai',
    tanggal: '2024-10-11',
    jam: '09:00',
    lokasi: 'Surabaya',
    detailjasa:
      'Tembok rumah di ruang tamu bocor akibat hujan, mohon perbaikan segera.',
    harga: 30000,
  },
  {
    id: 53,
    kategori: 'Pembersihan',
    userid: 78,
    nama: 'Putri Ayu',
    jasaid: 4,
    metode_pembayaran: 'Cash',
    status: 'Menunggu',
    tanggal: '2024-10-15',
    jam: '11:00',
    lokasi: 'Depok',
    detailjasa:
      'Butuh jasa bersih-bersih rumah dan kantor di daerah Margonda, tolong bersihkan seluruh ruangan.',
    harga: 120000,
  },
  {
    id: 54,
    kategori: 'Elektronik',
    userid: 79,
    nama: 'Hendra Wijaya',
    jasaid: 5,
    metode_pembayaran: 'Transfer',
    status: 'Berjalan',
    tanggal: '2024-10-13',
    jam: '08:30',
    lokasi: 'Yogyakarta',
    detailjasa:
      'Lampu rumah mati total, butuh bantuan untuk memperbaiki instalasi listrik.',
    harga: 150000,
  },
  {
    id: 55,
    kategori: 'Perbaikan Rumah',
    userid: 80,
    nama: 'Joko Pranoto',
    jasaid: 6,
    metode_pembayaran: 'Cash',
    status: 'Selesai',
    tanggal: '2024-10-09',
    jam: '15:00',
    lokasi: 'Medan',
    detailjasa:
      'Atap rumah saya bocor, perlu segera diperbaiki karena hujan akan datang.',
    harga: 160000,
  },
  {
    id: 56,
    kategori: 'Pertukangan',
    userid: 81,
    nama: 'Rina Setiani',
    jasaid: 7,
    metode_pembayaran: 'Transfer',
    status: 'Menunggu',
    tanggal: '2024-10-16',
    jam: '07:30',
    lokasi: 'Bekasi',
    detailjasa: 'Kran air di dapur bocor, tolong segera perbaiki.',
    harga: 100000,
  },
  {
    id: 57,
    kategori: 'Pengantaran',
    userid: 82,
    nama: 'Faisal Kurnia',
    jasaid: 8,
    metode_pembayaran: 'Cash',
    status: 'Berjalan',
    tanggal: '2024-10-14',
    jam: '13:00',
    lokasi: 'Tangerang',
    detailjasa:
      'Antar barang elektronik ke alamat rumah saya yang ada di Pondok Aren.',
    harga: 75000,
  },
  {
    id: 58,
    kategori: 'Hewan Peliharaan',
    userid: 83,
    nama: 'Agus Salim',
    jasaid: 9,
    metode_pembayaran: 'Transfer',
    status: 'Selesai',
    tanggal: '2024-10-10',
    jam: '16:00',
    lokasi: 'Semarang',
    detailjasa:
      'Grooming untuk anjing saya, tolong potong kuku dan bersihkan bulu.',
    harga: 75000,
  },
  {
    id: 59,
    kategori: 'Perawatan Taman',
    userid: 84,
    nama: 'Dian Sasmita',
    jasaid: 10,
    metode_pembayaran: 'Cash',
    status: 'Menunggu',
    tanggal: '2024-10-15',
    jam: '08:00',
    lokasi: 'Malang',
    detailjasa:
      'Pemotongan rumput dan perawatan taman agar halaman rumah terlihat lebih rapi.',
    harga: 200000,
  },
  {
    id: 60,
    kategori: 'Perbaikan Rumah',
    userid: 85,
    nama: 'Andi Wirawan',
    jasaid: 11,
    metode_pembayaran: 'Transfer',
    status: 'Berjalan',
    tanggal: '2024-10-12',
    jam: '09:30',
    lokasi: 'Jakarta',
    detailjasa: 'Sedot WC untuk rumah di kawasan Jakarta Selatan.',
    harga: 200000,
  },
  {
    id: 61,
    kategori: 'Pengantaran',
    userid: 86,
    nama: 'Siti Mulyani',
    jasaid: 12,
    metode_pembayaran: 'Cash',
    status: 'Selesai',
    tanggal: '2024-10-11',
    jam: '10:30',
    lokasi: 'Surabaya',
    detailjasa: 'Antar barang ke kantor saya yang berada di kawasan Gubeng.',
    harga: 40000,
  },
  {
    id: 62,
    kategori: 'Pengantaran',
    userid: 87,
    nama: 'Rudi Hartono',
    jasaid: 13,
    metode_pembayaran: 'Transfer',
    status: 'Menunggu',
    tanggal: '2024-10-13',
    jam: '13:30',
    lokasi: 'Medan',
    detailjasa: 'Antar barang ke rumah saya di Jalan Sisingamangaraja.',
    harga: 42000,
  },
  {
    id: 63,
    kategori: 'Perawatan Taman',
    userid: 88,
    nama: 'Bayu Pratama',
    jasaid: 14,
    metode_pembayaran: 'Cash',
    status: 'Selesai',
    tanggal: '2024-10-10',
    jam: '16:30',
    lokasi: 'Jakarta',
    detailjasa: 'Perawatan taman dan pemangkasan rumput di halaman rumah.',
    harga: 80000,
  },
  {
    id: 64,
    kategori: 'Perawatan Taman',
    userid: 89,
    nama: 'Tono Setiawan',
    jasaid: 15,
    metode_pembayaran: 'Transfer',
    status: 'Menunggu',
    tanggal: '2024-10-12',
    jam: '10:30',
    lokasi: 'Bandung',
    detailjasa:
      'Perawatan taman, pemangkasan daun kering, dan penyiraman tanaman.',
    harga: 85000,
  },
];
