-- AlterTable
ALTER TABLE `order` MODIFY `status` ENUM('PENDING', 'ACCEPTED', 'PROCCESSED', 'COMPLETED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
    MODIFY `payment_status` ENUM('PENDING', 'COMPLETED', 'FAILED') NOT NULL DEFAULT 'PENDING';
